### ISSUE TITLE
Develop initial release of sqlite-parser

### ISSUE THREAD

**Issue by nwronski** [codeschool/sqlite-parser#1]
# Milestones for sqlite-parser
## **[0.1.0]** Finished
- [x] `SELECT`
  - [x] Sub-queries
    
    ``` sql
    SELECT *
    FROM (
      SELECT *
      FROM b
    ) AS z
    ```
    - [x] _Has spec_
  - [x] Functions `SUM()`, aggregation `*`, etc...
    
    ``` sql
    SELECT COUNT(*)
    FROM apples
    ```
    - [x] _Has spec_
  - [x] Compound queries
    
    ``` sql
    SELECT *
    FROM a
    UNION
    SELECT *
    FROM b
    ```
    - [x] _Has spec_
  - [x] Alternate syntax
    
    ``` sql
    VALUES (1, 2, 'hat')
    ORDER BY id DESC
    ```
    - [x] _Has spec_
  - [x] `JOIN` types `INNER`, `OUTER`, `LEFT`
    - [x] Joins on tables and/or sub-queries
      - [x] _Has spec_
    - [x] `USING`
      
      ``` sql
      SELECT *
      FROM bees
        JOIN inventory AS i USING i.name, i.type
      ```
      - [ ] _Has spec_
  - [x] Query modifiers `WHERE`, `GROUP BY`, `HAVING`
    - [x] `WHERE`
      - [ ] _Has spec_
    - [x] `FROM`
      - [ ] _Has spec_
    - [x] `ORDER BY`
      - [ ] _Has spec_
    - [x] `GROUP BY`
      - [ ] _Has spec_
    - [x] `HAVING`  
      - [ ] _Has spec_
    - [x] `LIMIT`
      - [ ] _Has spec_
- [x] `INSERT`
  - [x] Basic
    
    ``` sql
    INSERT INTO bees (a, b, c)
    VALUES (1, 2, 'hey'), (2, 3, 'yo')
    ```
    - [x] _Has spec_
  - [x] Default values
    
    ``` sql
    INSERT INTO apples (a, b, c)
    DEFAULT VALUES
    ```
    - [x] _Has spec_
  - [x] Insert into select
    
    ``` sql
    INSERT INTO apples (a, b, c)
    SELECT * FROM apples
    ```
    - [x] _Has spec_
- [x] `UPDATE`
  - [x] Basic format
    - [x] _Has spec_
  - [x] Limit update format
    - [x] _Has spec_
- [x] `DELETE`
  - [x] Basic format
    - [x] _Has spec_
  - [x] Limit update format
    - [x] _Has spec_
- [x] `DROP`
  - [x] _Has spec_
- [x] `CREATE`
  - [x] Table format
    - [x] Basic format
      - [x] _Has spec_
      - [x] Table constraints
        - [x] `PRIMARY KEY`
          - [x] _Has spec_
        - [x] `CHECK`
          - [x] _Has spec_
        - [x] `FOREIGN KEY`
          - [x] _Has spec_
      - [x] Column constraints
        - [x] `PRIMARY KEY`
          - [x] _Has spec_  
        - [x] `NOT NULL`, `UNIQUE`
          - [x] _Has spec_  
        - [x] `CHECK`
          - [x] _Has spec_  
        - [x] `DEFAULT`
          - [ ] _Has spec_  
        - [x] `COLLATE`
          - [ ] _Has spec_  
        - [x] `FOREIGN KEY`
          - [x] _Has spec_  
  - [x] Create table `AS SELECT`
    - [x] _Has spec_
- [x] `ALTER TABLE`
  - [ ] _Has spec_
- [x] Transaction statement types
  
  ``` sql
  BEGIN IMMEDIATE TRANSACTION
  CREATE TABLE foods (
    id int PRIMARY KEY,
    item varchar(50),
    size varchar(15),
    price int
  );
  
  INSERT INTO foods (item, size, id, price)
    SELECT 'banana', size, null, price
    FROM bananas
    WHERE color != 'red'
  
  COMMIT
  ```
  - [x] `BEGIN`
    - [x] _Has spec_
  - [x] `COMMIT`, `END`
    - [x] _Has spec_
  - [x] `ROLLBACK`
    - [x] _Has spec_
- [x] Query plan `EXPLAIN QUERY PLAN stmt`
  - [ ] _Has spec_
- [x] Multiple queries in batch
  
  ``` sql
  CREATE TABLE Actors (
    name varchar(50),
    country varchar(50),
    salary integer
  );
  
  INSERT INTO Actors (name, country, salary) VALUES
    ('Vivien Leigh', 'IN', 150000),
    ('Clark Gable', 'USA', 120000),
    ('Olivia de Havilland', 'Japan', 30000),
    ('Hattie McDaniel', 'USA', 45000);
  ```
  - [x] Full-featured (multiple, related statements) tests _(have: 2)_
- [x] Indexed sources in queries
  
  ``` sql
  SELECT *
  FROM bees AS b INDEXED BY bees_index
  ```
  - [x] _Has spec_
- [x] Comments
  - [x] Line comments
    
    ``` sql
    SELECT *
    FROM hats --happy table
    WHERE color = 'black'
    ```
    - [x] _Has spec_
  - [x] Block comments
    
    ``` sql
    /*
    * This is a /* nested */
    * C-style block comment as allowed
    * in SQL spec
    */
    SELECT *
    FROM hats
    WHERE color = 'black'
    ```
    - [x] _Has spec_
- [x] Aliases `SELECT * FROM apples AS a`
  - [x] `apples AS unquoted_name`
    - [x] _Has spec_
  - [x] `apples no_as`
    - [x] _Has spec_
  - [x] `apples containsWhereKeyword` and `apples AS floatDatatype`
    - [x] _Has spec_
    - [x] **BUG**: Currently, paradoxically working for all keywords everything except `INT`, `INTEGER`, `INT2` but still working for `BIGINT`, `MEDIUMINT`...
      - **FIXED: fixed by changing order of reserved_nodes rule symbols**
    - [x] Do not allow **unquoted** alias as exact match for a keyword or datatype name `apples AS VARCHAR`, `apples AS Join`
  - [x] `apples AS [inBrackets]`
    - [x] _Has spec_
  - [x] `apples AS `backticks``
    - [x] _Has spec_
  - [x] `apples AS "Double Quoted with Spaces"`
    - [x] _Has spec_
  - [x] **Single-quoted aliases are invalid in most SQL dialects**
    
    ``` sql
    SELECT hat AS 'The Hat'
    FROM dinosaurs
    ```
- [ ] Expressions  
  - [x] `CAST banana AS INT`
    - [x] _Has spec_
  - [x] `CASE`
    
    ``` sql
    SELECT CASE WHEN apple > 1 THEN 'YES' ELSE 'NO' END
    FROM apples
    ```
    - [x] _Has spec_
  - [x] Binary `IN`
    
    ``` sql
    SELECT *
    FROM hats
    WHERE bees NOT IN (SELECT * FROM apples)
    ```
    - [x] _Has spec_
  - [x] Unary
    
    ``` sql
    SELECT NOT bees AS [b]
    FROM hats
    ```
    - [x] _Has spec_
  - [x] `RAISE`
    
    ``` sql
    RAISE (ROLLBACK, 'hey there!')
    ```
    - [ ] _Has spec_
  - [x] `COLLATE`
    
    ``` sql
    bees COLLATE bees_collation
    ```
    - [ ] _Has spec_
  - [x] `LIKE`
    
    ``` sql
    SELECT *
    FROM hats
    WHERE bees LIKE '%somebees%'
    ```
    - [x] _Has spec_
  - [x] `ESCAPE`
    
    ``` sql
    SELECT bees NOT LIKE '%hive' ESCAPE hat > 1
    FROM hats
    ```
    - [ ] _Has spec_
  - [x] Binary `IS`, `IS NOT`
    
    ``` sql
    SELECT *
    FROM hats
    WHERE ham IS NOT NULL
    ```
    - [x] _Has spec_
  - [x] `BETWEEN`
    
    ``` sql
    SELECT *
    FROM hats
    WHERE x BETWEEN 2 AND 3
    ```
    - [ ] _Has spec_
  - [x] Expression lists
    
    ``` sql
    SELECT expr1, expr2, expr3
    FROM hats
    ```
    - [x] _Has spec_
  - [x] Binary operation
    
    ``` sql
    SELECT *
    FROM hats
    WHERE 2 != 3
    ```
    - [x] _Has spec_
  - [x] Functions
    
    ``` sql
    SELECT MYFUNC(col, 1.2, 'str')
    ```
    - [x] _Has spec_
  - [x] Table expressions
    
    ``` sql
    WITH ham AS (
      SELECT type
      FROM hams
    )
    SELECT *
    FROM inventory
      INNER JOIN ham
        ON inventory.variety = ham.type
    ```
    - [x] _Has spec_
  - [x] Logical grouping `1 == 2 AND 2 == 3`
    - [x] _Has spec_
    - [x] **BUG**: Need to fix the grouping of expressions to allow for expressions to be logically organized.
      - Example:
        
        ``` sql
        SELECT *
        FROM bees
        WHERE 1 < 2 AND 3 < 4
        ```
        
        > ```
        > 
        >           AND                            <
        >       /         \         versus     /       \
        >      <           <                  1        AND
        >   /     \     /     \                      /     \
        >  1       2   3       4                    2       <
        >                                                /     \
        >                                               3       4
        > ```
      - **FIXED: now grouping correctly when using binary AND / OR**
- [x] Literals
  - [x] `'string'`
    - [ ] _Has spec_
  - [x] Decimal, Hex, Exponent `12`, `1.2`, `1E-9`, `0xe1e3`
    - [ ] _Has spec_
  - [x] Signed number `-2.001`
    - [ ] _Has spec_
- [x] Bind parameters
  - [x] Numbered `?`, `?12`
    - [ ] _Has spec_
  - [x] Named `@bees`
    - [ ] _Has spec_
  - [x] TCL `$hey "Hey There"`
    - [ ] _Has spec_
- [x] BLOB `X'stuff'`
  - [ ] _Has spec_
- AST
  - [x] Initial AST Format
    
    ``` json
    {
      "statement": [
        {
          "type": "statement",
          "variant": "select"
        },
        {
          "type": "statement",
          "variant": "create"
        }
      ]
    }
    ```
  - [ ] **BUG: AST should output normalized (lowercased) values for case-insentive data (e.g.: datatypes, keywords, etc...)**
  - [ ] **ISSUE:** Need to normalize format across all statement types (e.g.: `CREATE TABLE`, `SELECT`)
    - [ ] Normalize `CREATE`, `SELECT`, `INSERT`, `UPDATE`, `DROP`, `DELETE`
    - [x] Constraint versus Clause versus Condition (Table Constraint, Column Constraint, etc...)
- [ ] Datatypes
  - [x] SQLite
    
    | Expression | Resulting Affinity |
    | :-- | --: |
    | INT | INTEGER |
    | INTEGER | INTEGER |
    | TINYINT | INTEGER |
    | SMALLINT | INTEGER |
    | MEDIUMINT | INTEGER |
    | BIGINT | INTEGER |
    | UNSIGNED BIG | INTEGER |
    | INT2 | INTEGER |
    | INT8 | INTEGER |
    | CHARACTER(20) | TEXT |
    | VARCHAR(255) | TEXT |
    | VARYING CHARACTER(255) | TEXT |
    | NCHAR(55) | TEXT |
    | NATIVE CHARACTER(70) | TEXT |
    | NVARCHAR(100) | TEXT |
    | TEXT | TEXT |
    | CLOB | TEXT |
    | BLOB | NONE |
    | no datatype specified | NONE |
    | REAL | REAL |
    | DOUBLE | REAL |
    | DOUBLE PRECISION | REAL |
    | FLOAT | REAL |
    | NUMERIC | NUMERIC |
    | DECIMAL(10,5) | NUMERIC |
    | BOOLEAN | NUMERIC |
    | DATE | NUMERIC |
    | DATETIME | NUMERIC |
